/**
 * `@sinete/ibs-cbs`: o motor do IBS e da CBS do sinete, agnóstico de documento (NF-e, NFC-e, CT-e, NFCom, NFS-e...).
 *
 * A raiz reexporta as quatro partes; quem quer só uma importa o subpath:
 * - `@sinete/ibs-cbs/aliquotas`: alíquotas nominais por data de fato gerador, com estado da fonte;
 * - `@sinete/ibs-cbs/calcular`: cálculo a partir de uma operação já classificada (CST e cClassTrib por item);
 * - `@sinete/ibs-cbs/validar`: regras de validação da NT 2025.002 que dá para conferir sem o banco da SEFAZ;
 * - `@sinete/ibs-cbs/determinar`: determinação do CST e do cClassTrib a partir de fatos de negócio.
 *
 * Os dados oficiais (CST, cClassTrib, tratamentos, anexos) ficam no `@sinete/ibs-cbs-dados`, que tem ritmo de versão
 * próprio (ADR 0007 e ADR 0008).
 */

export type {
  Aliquota,
  AliquotaInformada,
  AliquotasNominais,
  DataIso,
  Dec,
  FonteDaAliquota,
  Local,
  ProvedorDeAliquotas,
  RegistroAliquotaDeReferencia,
  RegistroAliquotaPadrao,
  SituacaoDaAliquota,
  TabelaDeAliquotas,
  TributoDaAliquota,
  Vigencia,
} from './aliquotas/index.ts';
export {
  aliquotasOficiais,
  comAliquotasInformadas,
  ErroAliquotaDesconhecida,
  ErroDadosDeAliquotas,
  ehSimulada,
  exigirAliquota,
  TABELA_ALIQUOTAS,
  TRIBUTOS_DAS_ALIQUOTAS,
  VERSAO_DO_FORMATO_DAS_ALIQUOTAS,
} from './aliquotas/index.ts';
export type {
  AliquotaAplicada,
  AliquotasInformadas,
  CalcularOpcoes,
  CompraGovernamental,
  CreditoPresumido,
  CreditoPresumidoTributo,
  CreditoPresumidoZfm,
  EntradaDoRastro,
  GCBS,
  GCredPresIBSZFM,
  GCredPresOper,
  GCredPresTributo,
  GDevTrib,
  GDif,
  GIBSCBS,
  GIBSMun,
  GIBSUF,
  GRed,
  GTribCompraGov,
  GTribRegular,
  IBSCBS,
  IBSCBSTot,
  ItemClassificado,
  LocalDaOperacao,
  MotivoErroClassificacao,
  OperacaoClassificada,
  OrigemDaAliquota,
  RegimeNaoSuportado,
  Roc,
  RocItem,
  RoundingMode,
  TpEnteGov,
  TributacaoRegular,
  ValoresCompraGov,
  Variaveis,
} from './calcular/index.ts';
export {
  avaliar,
  calcular,
  calcularEm,
  conferirExpressao,
  Decimal,
  dec,
  dePercentual,
  dinheiro,
  ErroClassificacao,
  ErroExpressao,
  ErroRegimeNaoSuportado,
  ESCALA_INTERNA,
  enteDe,
  paraPercentual,
  percentual,
  REDISTRIBUICAO_A_PARTIR_DE,
  redistribuir,
  sum,
  VARIAVEIS_DAS_EXPRESSOES,
} from './calcular/index.ts';
export type {
  Candidato,
  ContextoDoResolvedor,
  ContextoRegraLegal,
  Determinacao,
  DeterminacaoDoItem,
  DeterminarEmOpcoes,
  DeterminarOpcoes,
  EntradaDaOperacao,
  EntradaDoItem,
  Exclusao,
  FatosDaOperacao,
  FatosDaParte,
  FatosDoItem,
  MotivoDaExclusao,
  MotivoErroDeterminacao,
  OpcaoDaPergunta,
  PerfilDoItem,
  Pergunta,
  Procedencia,
  RegraAplicada,
  RegraLegal,
  Resolvedor,
  RestricoesDoItem,
  RestringirOpcoes,
  ResultadoDoResolvedor,
  ResultadoRegraLegal,
  TipoDeOperacao,
} from './determinar/index.ts';
export {
  ATOR_PRODUTOR_RURAL_NAO_CONTRIBUINTE,
  candidatoDe,
  candidatoUnico,
  dataDoFato,
  determinar,
  determinarEm,
  doPerfil,
  ErroDeterminacao,
  idDaPergunta,
  paraClassificado,
  perguntarAoUsuario,
  REGRAS_LEGAIS,
  RESOLVEDORES_PADRAO,
  restringir,
  restringirEm,
} from './determinar/index.ts';
export type {
  Ambiente,
  Ativacao,
  ContextoDaRegra,
  DescricaoDaRegra,
  DocumentoDasRegras,
  ItemDasRegras,
  Modelo,
  NaoImplementada,
  Regra,
  Relatar,
  RelatorioDeValidacao,
  TabelasNt,
  ValidarOpcoes,
  Violacao,
} from './validar/index.ts';
export { ativa, documentoDoRoc, NAO_IMPLEMENTADAS, REGRAS, TABELAS_NT, validar } from './validar/index.ts';
