/**
 * `@sinete/ibs-cbs`: o motor do IBS e da CBS do sinete, agnóstico de documento (NF-e, NFC-e, CT-e, NFCom, NFS-e...).
 *
 * A raiz reexporta as quatro partes; quem quer só uma importa o subpath:
 * - `@sinete/ibs-cbs/aliquotas`: alíquotas nominais por data de fato gerador, com estado da fonte;
 * - `@sinete/ibs-cbs/calcular`: cálculo a partir de uma operação já classificada (CST e cClassTrib por item);
 * - `@sinete/ibs-cbs/validar`: regras de validação da NT 2025.002 que dá para conferir sem o banco da SEFAZ;
 * - `@sinete/ibs-cbs/determinar`: determinação do CST e do cClassTrib a partir de fatos de negócio.
 *
 * Os dados oficiais (CST, cClassTrib, tratamentos, anexos) ficam no `@sinete/ibs-cbs-dados`, que tem ritmo de versão
 * próprio (ADR 0007 e ADR 0008).
 */

export type {
  Dec,
  IsoDate,
  NominalRates,
  Place,
  Rate,
  RateOverride,
  RateProvider,
  RateSource,
  RateStatus,
  RatesTable,
  RateTributo,
  ReferenceRateRecord,
  StandardRateRecord,
  Validity,
} from './aliquotas/index.ts';
export {
  isSimulated,
  officialRates,
  RATE_TRIBUTOS,
  RATES_SCHEMA_VERSION,
  RATES_TABLE,
  RatesDataError,
  RateUnknownError,
  requireRate,
  withOverrides,
} from './aliquotas/index.ts';
export type {
  AppliedRate,
  CalculateOptions,
  ClassificationReason,
  ClassifiedItem,
  ClassifiedOperation,
  GCBS,
  GCredPresIBSZFM,
  GCredPresOper,
  GCredPresTributo,
  GDevTrib,
  GDif,
  GIBSCBS,
  GIBSMun,
  GIBSUF,
  GovernmentPurchase,
  GovValues,
  GRed,
  GTribCompraGov,
  GTribRegular,
  IBSCBS,
  IBSCBSTot,
  InformedRates,
  OperationPlace,
  PresumedCredit,
  PresumedCreditTributo,
  RateOrigin,
  RegularTaxation,
  Roc,
  RocItem,
  RoundingMode,
  TpEnteGov,
  TraceEntry,
  UnsupportedRegime,
  Variables,
  ZfmPresumedCredit,
} from './calcular/index.ts';
export {
  ClassificationError,
  calculate,
  calculateAt,
  checkExpression,
  Decimal,
  dec,
  EXPRESSION_VARIABLES,
  ExpressionError,
  enteOf,
  evaluate,
  fromPercent,
  INTERNAL_SCALE,
  money,
  percent,
  REDISTRIBUTION_FROM,
  redistribute,
  sum,
  toPercent,
  UnsupportedRegimeError,
} from './calcular/index.ts';
export type {
  AppliedRule,
  Candidate,
  ConstrainOptions,
  Determination,
  DeterminationReason,
  DetermineAtOptions,
  DetermineOptions,
  Exclusion,
  ExclusionReason,
  ItemConstraints,
  ItemDetermination,
  ItemFacts,
  ItemInput,
  ItemProfile,
  LegalOutcome,
  LegalRule,
  LegalRuleContext,
  OperationFacts,
  OperationInput,
  OperationKind,
  PartyFacts,
  Provenance,
  Question,
  QuestionOption,
  ResolveContext,
  Resolver,
  ResolverOutcome,
} from './determinar/index.ts';
export {
  ACTOR_RURAL_PRODUCER_NON_CONTRIBUTOR,
  askUser,
  candidateOf,
  constrain,
  constrainAt,
  DEFAULT_RESOLVERS,
  DeterminationError,
  determine,
  determineAt,
  factDate,
  fromProfile,
  LEGAL_RULES,
  questionId,
  toClassified,
  uniqueCandidate,
} from './determinar/index.ts';
export type {
  Activation,
  Ambiente,
  Modelo,
  NotImplemented,
  NtTables,
  Report,
  Rule,
  RuleContext,
  RuleMeta,
  RulesDocument,
  RulesItem,
  ValidateOptions,
  ValidationReport,
  Violation,
} from './validar/index.ts';
export { documentFromRoc, isActive, NOT_IMPLEMENTED, NT_TABLES, RULES, validate } from './validar/index.ts';
