#!/usr/bin/env bun
/**
 * Gera `internal/policy/data_gen.go` a partir dos dados versionados do repositório (ADR 0005, decisão 5): a lista
 * fechada de hosts por ambiente (`hostsDoAmbiente` do `@sinete/transport`), os hosts cujo perfil TLS medido só oferece
 * DHE, que no Go viram troca de chave RSA (`tls-profiles.json`), e as ACs ICP-Brasil que entram na confiança TLS
 * (`pemTlsIcpBrasil` do `@sinete/cert`). O helper compila esses dados: mudar a lista de hosts exige release.
 *
 * Uso: bun helpers/signer-tls/scripts/gen-data.ts           (escreve)
 *      bun helpers/signer-tls/scripts/gen-data.ts --check   (falha fora de sincronia; roda no `bun run check`)
 */
import path from 'node:path';
import process from 'node:process';
import { ICP_BRASIL_BUNDLE, pemTlsIcpBrasil } from '../../../packages/cert/src/bundle.ts';
import { DADOS_DE_ENDPOINTS, hostsDoAmbiente, perfisTls } from '../../../packages/transport/src/endpoints.ts';

const out = path.join(import.meta.dir, '../internal/policy/data_gen.go');
const check = process.argv.includes('--check');

const goString = (s: string): string => JSON.stringify(s);
const goList = (xs: readonly string[]): string => xs.map((x) => `\t\t${goString(x)},`).join('\n');

const homologacao = hostsDoAmbiente('homologacao');
const producao = hostsDoAmbiente('producao');
const rsaKex = perfisTls()
  .filter((p) => p.trocaDeChaves === 'dhe')
  .map((p) => p.host)
  .sort();
const pems = pemTlsIcpBrasil();

const text = `// Code generated by helpers/signer-tls/scripts/gen-data.ts; DO NOT EDIT.

package policy

// DataVersion identifica os dados compilados: endpoints, perfis TLS e bundle ICP-Brasil.
const DataVersion = ${goString(`endpoints ${DADOS_DE_ENDPOINTS.versaoDosEndpoints}; perfis ${DADOS_DE_ENDPOINTS.versaoDosPerfisTls}; icp ${ICP_BRASIL_BUNDLE.versao}`)}

// hostsByAmbiente é a lista fechada de hosts por ambiente, a mesma de hostsDoAmbiente() do @sinete/transport.
var hostsByAmbiente = map[string][]string{
\t"homologacao": {
${goList(homologacao)}
\t},
\t"producao": {
${goList(producao)}
\t},
}

// rsaKexHosts são os hosts cujo perfil medido só oferece troca DHE, que o crypto/tls não implementa. Para eles, e só
// para eles, o helper oferece também a troca de chave RSA (ADR 0005, seção 2 da evidência).
var rsaKexHosts = map[string]bool{
${rsaKex.map((h) => `\t${goString(h)}: true,`).join('\n')}
}

// icpBrasilTLS são as ACs ICP-Brasil da confiança TLS (raízes v5, v10, v11 e v12 e as intermediárias SSL vistas),
// somadas à loja do sistema para validar o certificado do servidor.
const icpBrasilTLS = ${pems.map((p) => `\`${p.trim()}\n\``).join(' +\n\t')}
`;

if (check) {
  const current = await Bun.file(out)
    .text()
    .catch(() => '');
  if (current !== text) {
    console.error(
      `${path.relative(process.cwd(), out)} fora de sincronia: rode bun helpers/signer-tls/scripts/gen-data.ts`,
    );
    process.exit(1);
  }
  console.log('gen-data: data_gen.go em sincronia');
} else {
  await Bun.write(out, text);
  console.log(
    `gen-data: ${homologacao.length} hosts de homologação, ${producao.length} de produção, ${rsaKex.length} com troca RSA, ${pems.length} ACs`,
  );
}
