/** Códigos estáveis das ocorrências dos validadores (API pública: renomear é major). */
export const CODIGOS_OCORRENCIA = [
  'cpf_caractere_invalido',
  'cpf_tamanho_invalido',
  'cpf_digitos_repetidos',
  'cpf_dv_invalido',
  'cpf_base_invalida',
  'cnpj_caractere_invalido',
  'cnpj_tamanho_invalido',
  'cnpj_formato_invalido',
  'cnpj_digitos_repetidos',
  'cnpj_dv_invalido',
  'cnpj_base_invalida',
  'caepf_caractere_invalido',
  'caepf_tamanho_invalido',
  'caepf_digitos_repetidos',
  'caepf_dv_invalido',
  'caepf_base_invalida',
  'chave_caractere_invalido',
  'chave_tamanho_invalido',
  'chave_formato_invalido',
  'chave_dv_invalido',
  'chave_uf_invalida',
  'chave_mes_invalido',
  'chave_ano_invalido',
  'chave_modelo_invalido',
  'chave_modelo_nao_suportado',
  'chave_numero_invalido',
  'chave_tpemis_invalido',
  'chave_serie_invalida',
  'chave_cnf_invalido',
  'chave_emitente_invalido',
  'chave_cnpj_alfanumerico_fora_da_vigencia',
  'chave_base_invalida',
  'ie_uf_invalida',
  'ie_isento_nao_permitido',
  'ie_caractere_invalido',
  'ie_zerada',
  'ie_tamanho_invalido',
  'ie_formato_invalido',
  'ie_dv_invalido',
  'ie_base_invalida',
] as const;

export type CodigoOcorrencia = (typeof CODIGOS_OCORRENCIA)[number];
